import type { Metadata } from "next";
import "./globals.css";
import connectDB from "@/lib/dbconnect";
import Header from "@/components/header";


export const metadata: Metadata = {
  title: "Blinks App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectDB();
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
